### ISSUE TITLE
cmd/fitgen: parse sdk version from C code

### ISSUE THREAD

**Issue by tormoder** [tormoder/fit#23]

**Comment by torgil** [comment]
What would be the purpose of this one?

**Comment by tormoder** [comment]
The thought is that is probably more reliable for `fitgen` to parse the SDK version from the C SDK code, rather than using the zip filename or user supplied input via a flag.

**Comment by torgil** [comment]
Thanks. That makes sense. I managed to interpret the issues to mean the parser would be written in c.

**Comment by tormoder** [comment]
Not worth the effort.
