### ISSUE TITLE
Parsing data or definition message failed, When I upgrade from 16.20 to 20.43

### ISSUE THREAD

**Issue by amuguelove** [tormoder/fit#28]
When I call 'fit.Decode' method,  I get the following error messages:

parsing definition message: validating Session failed: field 8: unknown base type 0X%!X(PANIC=runtime error: index out of range)

or
parsing data message: missing data definition message for local message number 10

or
parsing definition message: validating Session failed: field 9: type BaseSint32 is not compatible with profile type BaseUint32

**Comment by tormoder** [comment]
Hi. Thanks for the report.

Could you try again with the latest changes, use the following option and paste the output:

```go
file, err := fit.Decode(yourReader, fit.WithStdLogger())
```

**Comment by amuguelove** [comment]
ok, I will try again.

**Comment by amuguelove** [comment]
header decoded: size: 14 | protover: 16 | profver: 2050 | dsize: 34922 | dtype: .FIT | crc: 0xd02b
definition message parsed: local: 0 | global: FileId | arch: LittleEndian | fields: 7
parsed file_id message: {Activity Garmin 2432 3939536309 2017-12-14 05:30:05 +0000 UTC 65535 }
definition message parsed: local: 1 | global: FileCreator | arch: LittleEndian | fields: 2
definition message parsed: local: 2 | global: Event | arch: LittleEndian | fields: 6
definition message parsed: local: 3 | global: DeviceInfo | arch: LittleEndian | fields: 27
definition message parsed: local: 4 | global: MesgNum(22) | arch: LittleEndian | fields: 10
definition message parsed: local: 5 | global: MesgNum(141) | arch: LittleEndian | fields: 7
definition message parsed: local: 6 | global: DeviceSettings | arch: LittleEndian | fields: 69
definition message parsed: local: 7 | global: UserProfile | arch: LittleEndian | fields: 28
definition message parsed: local: 8 | global: MesgNum(147) | arch: LittleEndian | fields: 50
definition message parsed: local: 9 | global: MesgNum(79) | arch: LittleEndian | fields: 17
definition message parsed: local: 10 | global: Sport | arch: LittleEndian | fields: 10
definition message parsed: local: 11 | global: MesgNum(13) | arch: LittleEndian | fields: 41
definition message parsed: local: 12 | global: ZonesTarget | arch: LittleEndian | fields: 11
definition message parsed: local: 13 | global: Record | arch: LittleEndian | fields: 5
definition message parsed: local: 14 | global: MesgNum(104) | arch: LittleEndian | fields: 5
definition message parsed: local: 15 | global: Record | arch: LittleEndian | fields: 3
definition message parsed: local: 0 | global: MesgNum(140) | arch: LittleEndian | fields: 27
definition message parsed: local: 1 | global: Lap | arch: LittleEndian | fields: 80
definition message parsed: local: 5 | global: MesgNum(216) | arch: LittleEndian | fields: 13
illegal definition message: local: 6 | global: Session | arch: LittleEndian | fields: 92

**Comment by amuguelove** [comment]
parsing definition message: validating Session failed: field 9: unknown base type: unknown (0x1F)

**Comment by amuguelove** [comment]
parsing definition message: validating Session failed: field 9: type BaseSint32 is not compatible with profile type BaseUint32
=======================================================================
header decoded: size: 14 | protover: 16 | profver: 2050 | dsize: 9917 | dtype: .FIT | crc: 0xa028
definition message parsed: local: 0 | global: FileId | arch: LittleEndian | fields: 7
parsed file_id message: {Activity Garmin 2697 3952360291 2017-12-13 04:21:34 +0000 UTC 65535 }
definition message parsed: local: 1 | global: FileCreator | arch: LittleEndian | fields: 2
definition message parsed: local: 2 | global: Event | arch: LittleEndian | fields: 6
definition message parsed: local: 3 | global: DeviceInfo | arch: LittleEndian | fields: 27
definition message parsed: local: 4 | global: MesgNum(22) | arch: LittleEndian | fields: 10
definition message parsed: local: 5 | global: MesgNum(141) | arch: LittleEndian | fields: 7
definition message parsed: local: 6 | global: DeviceSettings | arch: LittleEndian | fields: 69
definition message parsed: local: 7 | global: UserProfile | arch: LittleEndian | fields: 28
definition message parsed: local: 8 | global: MesgNum(147) | arch: LittleEndian | fields: 50
definition message parsed: local: 9 | global: MesgNum(79) | arch: LittleEndian | fields: 17
definition message parsed: local: 10 | global: Sport | arch: LittleEndian | fields: 10
definition message parsed: local: 11 | global: MesgNum(13) | arch: LittleEndian | fields: 41
definition message parsed: local: 12 | global: ZonesTarget | arch: LittleEndian | fields: 11
definition message parsed: local: 13 | global: Record | arch: LittleEndian | fields: 5
definition message parsed: local: 14 | global: Length | arch: LittleEndian | fields: 14
definition message parsed: local: 15 | global: MesgNum(104) | arch: LittleEndian | fields: 5
definition message parsed: local: 0 | global: Lap | arch: LittleEndian | fields: 80
definition message parsed: local: 1 | global: MesgNum(125) | arch: LittleEndian | fields: 5
definition message parsed: local: 4 | global: MesgNum(140) | arch: LittleEndian | fields: 27
illegal definition message: local: 5 | global: Session | arch: LittleEndian | fields: 92

**Comment by amuguelove** [comment]
parsing definition message: validating Session failed: field 9: unknown base type: unknown (0x1F)
=====================================
header decoded: size: 14 | protover: 16 | profver: 2050 | dsize: 53426 | dtype: .FIT | crc: 0xeffe
definition message parsed: local: 0 | global: FileId | arch: LittleEndian | fields: 7
parsed file_id message: {Activity Garmin 2691 3949585524 2017-12-13 22:46:49 +0000 UTC 65535 }
definition message parsed: local: 1 | global: FileCreator | arch: LittleEndian | fields: 2
definition message parsed: local: 2 | global: Event | arch: LittleEndian | fields: 6
definition message parsed: local: 3 | global: DeviceInfo | arch: LittleEndian | fields: 27
definition message parsed: local: 4 | global: MesgNum(22) | arch: LittleEndian | fields: 10
definition message parsed: local: 5 | global: MesgNum(141) | arch: LittleEndian | fields: 7
definition message parsed: local: 6 | global: DeviceSettings | arch: LittleEndian | fields: 69
definition message parsed: local: 7 | global: UserProfile | arch: LittleEndian | fields: 28
definition message parsed: local: 8 | global: MesgNum(79) | arch: LittleEndian | fields: 17
definition message parsed: local: 9 | global: Sport | arch: LittleEndian | fields: 10
definition message parsed: local: 10 | global: MesgNum(13) | arch: LittleEndian | fields: 41
definition message parsed: local: 11 | global: ZonesTarget | arch: LittleEndian | fields: 11
definition message parsed: local: 12 | global: Record | arch: LittleEndian | fields: 12
definition message parsed: local: 13 | global: MesgNum(233) | arch: LittleEndian | fields: 1
definition message parsed: local: 14 | global: MesgNum(104) | arch: LittleEndian | fields: 5
definition message parsed: local: 15 | global: Record | arch: LittleEndian | fields: 13
definition message parsed: local: 0 | global: Lap | arch: LittleEndian | fields: 80
definition message parsed: local: 1 | global: MesgNum(216) | arch: LittleEndian | fields: 13
definition message parsed: local: 4 | global: MesgNum(140) | arch: LittleEndian | fields: 27
illegal definition message: local: 5 | global: Session | arch: LittleEndian | fields: 92

**Comment by amuguelove** [comment]
@tormoder

**Comment by tormoder** [comment]
Thanks @amuguelove, I will take a look at this as soon as I have time.

**Comment by tormoder** [comment]
I think this probably has been fixed by https://github.com/tormoder/fit/pull/54.

I'll reopen the issue if you report it's not the case.
