### ISSUE TITLE
monitoring message fields.

### ISSUE THREAD

**Issue by jgc234** [tormoder/fit#45]
A quick question - I'm trying to parse a monitoring file (monitoringB with heart rate data from a forerunner 35).  The heart_rate fields fail to parse.  The FIT profile shows 37 possible fields in the monitoring message (mesg_num 55), but the MonitoringMsg (messages.go) struct only has 12 of these fields defined or available.  These 12 looks fairly similar to the fields shown in the FIT File Types Description document (2.2), which also doesn't show the whole list of available fields stated in the message defined in the profile.  Any idea what's going on there?  There seems to be a discrepancy between the profile and the document, and the code roughly aligns with the document.

**Comment by tormoder** [comment]
The `heart_rate` field is, as far as I can tell, not enabled in the default profile (for 20.90).

You could try to generate your own profile using the `fitgen` tool and a profile definition from e.g. [here](https://github.com/tormoder/fit/tree/master/cmd/fitgen/internal/profile/testdata), and where you in the `messages` sheet set `1` in the `EXAMPLE` column for the `heart_rate` field (field def 27) of the `Monitoring` message (55). The the `fitgen` tool should include the field in the generated struct.
