### ISSUE TITLE
Handling of multiple `DeviceInfoMsg`s

### ISSUE THREAD

**Issue by usedbytes** [tormoder/fit#46]
Currently there is precisely one `DeviceInfoMsg`, and it lives in the `File`.
It looks like having multiple `DeviceInfoMsg`s is valid per the spec, and indeed a number of the testdata references include multiple `DeviceInfoMsg`s. This can be useful to track battery voltage over time, or for multiple devices.

The question is, how to support this? The simplest thing would be to just delete `DeviceInfo` from `File` and add a slice of them to the relevant file types (according to SDK 21.32.00 that's `ActivityFile`, `WeightFile`, `BloodPressureFile`, `MontoringAFile`, `MonitoringBFile`). However, that would break anyone that's relying on `File.DeviceInfo`.

So, I made a change which duplicates `DeviceInfoMsg`s into both `File.DeviceInfo` and a slice in the individual file types (usedbytes@17b8c4f88cb5b6c1b4c8e05481eec90a3ef75280) - however this causes a problem when a file is decoded and re-encoded. The last `DeviceInfoMsg` ends up in both the slice and `File.DeviceInfo`, which means it ends up duplicated when writing out. This could be avoided by just not writing out `File.DeviceInfo`, but that might be "surprising" for users. Checking `File.DeviceInfo` against each entry in the slice and avoiding duplicates would be possible but a bit ugly, because the writer is using reflection and we'd need a special case just for `DeviceInfo`.

So, the simplest looks like just removing `File.DeviceInfo`, but I'm wary of what breakage that might cause, next easiest would be skip `File.DeviceInfo` on write-out. Any thoughts/opinions?

**Comment by tormoder** [comment]
Thanks for spotting this.

I think I would prefer a breaking change here, i.e. remove `File.DeviceInfo` as you mention. The library still has 0 as major version, and Go modules dependency management should make it possible for users to migrate in a controlled manner.

 I would happily accept a patch for this, and tag a new release.

**Comment by usedbytes** [comment]
OK sounds good, I'll send a PR hopefully later this week.

**Comment by usedbytes** [comment]
Submitted. I didn't touch README as I wasn't sure what your plan for version number was, but perhaps it's worth adding a note there about the change?
