### ISSUE TITLE
access to heart rate and timestamp_16

### ISSUE THREAD

**Issue by Val8ska** [tormoder/fit#77]
Hi,

I would like to know if it's possible to have access to heart rate and timestamp_16 value in monitoringB fit file.
When I import my fit file in fitfile viewer or using fitparse python library, it works well.
Or did I miss a feature???
Thank you for your job,

**Comment by tormoder** [comment]
Hi.

The two fields you mention are not "enabled" in the default FIT SDK profile. I.e. they don't have a vaule of `1` in the `EXAMPLE` column in the SDK profile spreadsheet. The master branch of this repo is generated using the default profile and therefore don't contain those fields.

You can generate your own custom profile, see https://github.com/tormoder/fit/wiki/Custom-Product-Profiles.

(But, I am concidering creating a branch with everything contained in the offical SDK profile enabled to more easily answer questions like this one.)
