### ISSUE TITLE
Sport field does not decoded

### ISSUE THREAD

**Issue by softkot** [tormoder/fit#80]
In example file the sport filed does not decoded and show any data.

[12140177144.zip](https://github.com/tormoder/fit/files/12816938/12140177144.zip)

Meantime the [online tool](https://www.fitfileviewer.com/) shows those fileds.

![image](https://github.com/tormoder/fit/assets/5500358/333d787d-e630-4389-a108-b00d7d01c20b)

**Comment by tormoder** [comment]
Can you try with latest?
`go get github.com/tormod/fit@latest`

I merged #68 yesterday, but have not released a new version yet.

**Comment by softkot** [comment]
go get github.com/tormoder/fit@latest  does not work but go get github.com/tormoder/fit@master does! Thanks.

**Comment by softkot** [comment]
go get github.com/tormoder/fit@latest does not work but go get github.com/tormoder/fit@master does! Thanks.
